version: "3.8"
services:
    redis:
        image: redis:6.2.1-alpine
        container_name: redis
        restart: always
        environment:
            - REDIS_PASSWORD=redis_pass
        volumes:
            - $PWD/redis_db_data:/data
        ports:
            - 6379:6379
        networks:
            - internal
        # network_mode: host
    app:
        image: devnul/pocket_telegram_bot
        container_name: pocket_telegram_bot
        restart: always
        links:
            - redis
        env_file:
            - env/docker.env
        ports:
            - 8888:8888
        networks:
            - internal
networks:
    internal:
        driver: bridge