name: Docker publish
on:
    push:
        branches:
            - main
jobs:
    # Push image to GitHub Packages.
    # See also https://docs.docker.com/docker-hub/builds/
    push:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - uses: actions/checkout@v2

            - name: Build image
              run: docker build . --file dockerfile --tag devnul/pocket_telegram_bot

            - name: Log into registry
              run: docker login -u ${{ env.DOCKER_LOGIN }} -p ${{ env.DOCKER_PASSWORD }}

            - name: Push image
              run: |
                docker push devnul/pocket_telegram_bot:latest
